version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: reto-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: retoCAECV
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: reto-backend
    restart: unless-stopped

    depends_on:
      - postgres

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/retoCAECV
      DB_USER: postgres
      DB_PASSWORD: postgres

    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend

    container_name: reto-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: