# Nombre de la aplicación
spring.application.name=backend

# Base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Backend: Puerto y /api/... para que las llamadas al back siempre sean con /api
server.port=8080
server.servlet.context-path=/api