# Nombre de la aplicación
spring.application.name=backend

# Base de datos
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Backend: Puerto y /api/... para que las llamadas al back siempre sean con /api
server.port=${PORT:8080}
server.servlet.context-path=/api

# Configuracion de Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=orivaretocaecv@gmail.com
spring.mail.password=jtjj xpkp xybj vuki
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true